package com.gridgame.common.model

case class CharacterId(id: Byte, name: String)

object CharacterId {
  val Spaceman: CharacterId = CharacterId(0, "Spaceman")
  val Gladiator: CharacterId = CharacterId(1, "Gladiator")
  val Wraith: CharacterId = CharacterId(2, "Wraith")
  val Wizard: CharacterId = CharacterId(3, "Wizard")
  val Tidecaller: CharacterId = CharacterId(4, "Tidecaller")
  val Soldier: CharacterId = CharacterId(5, "Soldier")
  val Raptor: CharacterId = CharacterId(6, "Raptor")
  val Assassin: CharacterId = CharacterId(7, "Assassin")
  val Warden: CharacterId = CharacterId(8, "Warden")
  val Samurai: CharacterId = CharacterId(9, "Samurai")
  val PlagueDoctor: CharacterId = CharacterId(10, "PlagueDoctor")
  val Vampire: CharacterId = CharacterId(11, "Vampire")

  // Batch 1: Elemental
  val Pyromancer: CharacterId = CharacterId(12, "Pyromancer")
  val Cryomancer: CharacterId = CharacterId(13, "Cryomancer")
  val Stormcaller: CharacterId = CharacterId(14, "Stormcaller")
  val Earthshaker: CharacterId = CharacterId(15, "Earthshaker")
  val Windwalker: CharacterId = CharacterId(16, "Windwalker")
  val MagmaKnight: CharacterId = CharacterId(17, "MagmaKnight")
  val Frostbite: CharacterId = CharacterId(18, "Frostbite")
  val Sandstorm: CharacterId = CharacterId(19, "Sandstorm")
  val Thornweaver: CharacterId = CharacterId(20, "Thornweaver")
  val Cloudrunner: CharacterId = CharacterId(21, "Cloudrunner")
  val Inferno: CharacterId = CharacterId(22, "Inferno")
  val Glacier: CharacterId = CharacterId(23, "Glacier")
  val Mudslinger: CharacterId = CharacterId(24, "Mudslinger")
  val Ember: CharacterId = CharacterId(25, "Ember")
  val Avalanche: CharacterId = CharacterId(26, "Avalanche")

  // Batch 2: Undead/Dark
  val Necromancer: CharacterId = CharacterId(27, "Necromancer")
  val SkeletonKing: CharacterId = CharacterId(28, "SkeletonKing")
  val Banshee: CharacterId = CharacterId(29, "Banshee")
  val Lich: CharacterId = CharacterId(30, "Lich")
  val Ghoul: CharacterId = CharacterId(31, "Ghoul")
  val Reaper: CharacterId = CharacterId(32, "Reaper")
  val Shade: CharacterId = CharacterId(33, "Shade")
  val Revenant: CharacterId = CharacterId(34, "Revenant")
  val Gravedigger: CharacterId = CharacterId(35, "Gravedigger")
  val Dullahan: CharacterId = CharacterId(36, "Dullahan")
  val Phantom: CharacterId = CharacterId(37, "Phantom")
  val Mummy: CharacterId = CharacterId(38, "Mummy")
  val Deathknight: CharacterId = CharacterId(39, "Deathknight")
  val Shadowfiend: CharacterId = CharacterId(40, "Shadowfiend")
  val Poltergeist: CharacterId = CharacterId(41, "Poltergeist")

  // Batch 3: Medieval/Fantasy
  val Paladin: CharacterId = CharacterId(42, "Paladin")
  val Ranger: CharacterId = CharacterId(43, "Ranger")
  val Berserker: CharacterId = CharacterId(44, "Berserker")
  val Crusader: CharacterId = CharacterId(45, "Crusader")
  val Druid: CharacterId = CharacterId(46, "Druid")
  val Bard: CharacterId = CharacterId(47, "Bard")
  val Monk: CharacterId = CharacterId(48, "Monk")
  val Cleric: CharacterId = CharacterId(49, "Cleric")
  val Rogue: CharacterId = CharacterId(50, "Rogue")
  val Barbarian: CharacterId = CharacterId(51, "Barbarian")
  val Enchantress: CharacterId = CharacterId(52, "Enchantress")
  val Jester: CharacterId = CharacterId(53, "Jester")
  val Valkyrie: CharacterId = CharacterId(54, "Valkyrie")
  val Warlock: CharacterId = CharacterId(55, "Warlock")
  val Inquisitor: CharacterId = CharacterId(56, "Inquisitor")

  // Batch 4: Sci-Fi/Tech
  val Cyborg: CharacterId = CharacterId(57, "Cyborg")
  val Hacker: CharacterId = CharacterId(58, "Hacker")
  val MechPilot: CharacterId = CharacterId(59, "MechPilot")
  val Android: CharacterId = CharacterId(60, "Android")
  val Chronomancer: CharacterId = CharacterId(61, "Chronomancer")
  val Graviton: CharacterId = CharacterId(62, "Graviton")
  val Tesla: CharacterId = CharacterId(63, "Tesla")
  val Nanoswarm: CharacterId = CharacterId(64, "Nanoswarm")
  val Voidwalker: CharacterId = CharacterId(65, "Voidwalker")
  val Photon: CharacterId = CharacterId(66, "Photon")
  val Railgunner: CharacterId = CharacterId(67, "Railgunner")
  val Bombardier: CharacterId = CharacterId(68, "Bombardier")
  val Sentinel: CharacterId = CharacterId(69, "Sentinel")
  val Pilot: CharacterId = CharacterId(70, "Pilot")
  val Glitcher: CharacterId = CharacterId(71, "Glitcher")

  // Batch 5: Nature/Beast
  val Wolf: CharacterId = CharacterId(72, "Wolf")
  val Serpent: CharacterId = CharacterId(73, "Serpent")
  val Spider: CharacterId = CharacterId(74, "Spider")
  val Bear: CharacterId = CharacterId(75, "Bear")
  val Scorpion: CharacterId = CharacterId(76, "Scorpion")
  val Hawk: CharacterId = CharacterId(77, "Hawk")
  val Shark: CharacterId = CharacterId(78, "Shark")
  val Beetle: CharacterId = CharacterId(79, "Beetle")
  val Treant: CharacterId = CharacterId(80, "Treant")
  val Phoenix: CharacterId = CharacterId(81, "Phoenix")
  val Hydra: CharacterId = CharacterId(82, "Hydra")
  val Mantis: CharacterId = CharacterId(83, "Mantis")
  val Jellyfish: CharacterId = CharacterId(84, "Jellyfish")
  val Gorilla: CharacterId = CharacterId(85, "Gorilla")
  val Chameleon: CharacterId = CharacterId(86, "Chameleon")

  // Batch 6: Mythological
  val Minotaur: CharacterId = CharacterId(87, "Minotaur")
  val Medusa: CharacterId = CharacterId(88, "Medusa")
  val Cerberus: CharacterId = CharacterId(89, "Cerberus")
  val Centaur: CharacterId = CharacterId(90, "Centaur")
  val Kraken: CharacterId = CharacterId(91, "Kraken")
  val Sphinx: CharacterId = CharacterId(92, "Sphinx")
  val Cyclops: CharacterId = CharacterId(93, "Cyclops")
  val Harpy: CharacterId = CharacterId(94, "Harpy")
  val Griffin: CharacterId = CharacterId(95, "Griffin")
  val Anubis: CharacterId = CharacterId(96, "Anubis")
  val Yokai: CharacterId = CharacterId(97, "Yokai")
  val Golem: CharacterId = CharacterId(98, "Golem")
  val Djinn: CharacterId = CharacterId(99, "Djinn")
  val Fenrir: CharacterId = CharacterId(100, "Fenrir")
  val Chimera: CharacterId = CharacterId(101, "Chimera")

  // Batch 7: Specialist
  val Alchemist: CharacterId = CharacterId(102, "Alchemist")
  val Puppeteer: CharacterId = CharacterId(103, "Puppeteer")
  val Gambler: CharacterId = CharacterId(104, "Gambler")
  val Blacksmith: CharacterId = CharacterId(105, "Blacksmith")
  val Pirate: CharacterId = CharacterId(106, "Pirate")
  val Chef: CharacterId = CharacterId(107, "Chef")
  val Musician: CharacterId = CharacterId(108, "Musician")
  val Astronomer: CharacterId = CharacterId(109, "Astronomer")
  val Runesmith: CharacterId = CharacterId(110, "Runesmith")
  val Shapeshifter: CharacterId = CharacterId(111, "Shapeshifter")

  val DEFAULT: CharacterId = Spaceman

  def fromId(id: Byte): CharacterId =
    CharacterDef.all.map(_.id).find(_.id == id).getOrElse(DEFAULT)
}
