package com.gridgame.client.audio

import com.gridgame.common.model.{CharacterId, ProjectileType}

/** Picks the sound file for an attack.
  *
  * Two tables, in priority order:
  *
  *  1. `overrides` — keyed on (character, projectile type). A handful of
  *     projectile types are shared by characters whose fantasies have nothing in
  *     common: `TREMOR_SLAM` is a barbarian splitting the earth AND a wolf's
  *     howl AND a banshee's wail; `FIREBALL` is a wizard's fireball AND a chef's
  *     flambé AND an alchemist's thrown potion. Keying only on the projectile
  *     makes half the roster sound like somebody else, so those cases name a
  *     sound per character.
  *  2. `byType` — the projectile type's own sound, which covers everything else.
  *     Grouping mirrors GLProjectileRenderers' registry: types that share a
  *     visual share a sound.
  *
  * Sounds live in sounds/atk_*.wav and are generated by
  * scripts/generate_sounds.py — add an entry there and here together. */
object AbilitySounds {
  private val NO_CHAR: Byte = -1

  private val byType: Array[String] = new Array[String](256)
  private val overrides = new java.util.HashMap[Int, String]()

  private def set(sound: String, ids: Byte*): Unit =
    ids.foreach(id => byType(id & 0xFF) = sound)

  private def only(sound: String, character: CharacterId, id: Byte): Unit =
    overrides.put(key(character.id, id), sound)

  private def key(characterId: Byte, projectileType: Byte): Int =
    ((characterId & 0xFF) << 8) | (projectileType & 0xFF)

  // ── magic bolts ─────────────────────────────────────────────────────────
  set("atk_normal_bolt", ProjectileType.NORMAL)
  set("atk_arcane_bolt", ProjectileType.ARCANE_BOLT)
  set("atk_mystic_bolt", ProjectileType.MYSTIC_BOLT)
  set("atk_rune_bolt", ProjectileType.RUNE_BOLT)
  set("atk_star_bolt", ProjectileType.STAR_BOLT)
  set("atk_soul_bolt", ProjectileType.SOUL_BOLT, ProjectileType.SOUL_BOLT_HEAVY)
  set("atk_haunt_bolt", ProjectileType.HAUNT)
  set("atk_death_bolt", ProjectileType.DEATH_BOLT)
  set("atk_leech_bolt", ProjectileType.LEECH_BOLT)
  set("atk_shadow_bolt", ProjectileType.SHADOW_BOLT, ProjectileType.SHADOW_HAUNT)
  set("atk_plague_bolt", ProjectileType.PLAGUE_BOLT)
  set("atk_venom_bolt", ProjectileType.VENOM_BOLT, ProjectileType.VENOM_BOLT_LIGHT)
  set("atk_flame_bolt", ProjectileType.FLAME_BOLT, ProjectileType.FLAME_BOLT_HEAVY,
    ProjectileType.FLAME_BOLT_LIGHT)
  set("atk_ember_shot", ProjectileType.EMBER_SHOT)
  set("atk_magma_ball", ProjectileType.MAGMA_BALL)
  set("atk_frost_shard", ProjectileType.FROST_SHARD, ProjectileType.FROST_SHARD_LIGHT,
    ProjectileType.RICOCHET_SHARD)
  set("atk_ice_spike", ProjectileType.GLACIER_SPIKE)
  set("atk_mud_glob", ProjectileType.MUD_GLOB)
  set("atk_sand_shot", ProjectileType.SAND_SHOT)
  set("atk_charm_bolt", ProjectileType.CHARM)
  set("atk_nano_bolt", ProjectileType.NANO_BOLT)
  set("atk_echo_bolt", ProjectileType.ECHO_BOLT)
  set("atk_sting", ProjectileType.STING)
  set("atk_holy_bolt", ProjectileType.HOLY_BOLT, ProjectileType.HOLY_BOLT_HEAVY)
  set("atk_smite", ProjectileType.SMITE)
  set("atk_curse_hex", ProjectileType.CURSE)
  set("atk_void_bolt", ProjectileType.VOID_BOLT)
  set("atk_gravity_ball", ProjectileType.GRAVITY_BALL, ProjectileType.GRAVITY_WELL,
    ProjectileType.GRAVITY_LOCK)
  set("atk_data_bolt", ProjectileType.DATA_BOLT)
  set("atk_virus_glitch", ProjectileType.VIRUS)

  // ── beams ───────────────────────────────────────────────────────────────
  set("atk_beam_ice", ProjectileType.ICE_BEAM)
  set("atk_beam_laser", ProjectileType.LASER, ProjectileType.LASER_HEAVY, ProjectileType.LASER_LIGHT)
  set("atk_beam_railgun", ProjectileType.RAILGUN)
  set("atk_sniper_beam", ProjectileType.SNIPER_BEAM)
  set("atk_beam_drain", ProjectileType.BLOOD_SIPHON, ProjectileType.SOUL_DRAIN, ProjectileType.LIFE_DRAIN)
  set("atk_beam_vine", ProjectileType.VINE_WHIP)
  set("atk_beam_stone", ProjectileType.STONE_GAZE, ProjectileType.PETRIFY)
  set("atk_beam_whip", ProjectileType.BANDAGE_WHIP)
  set("atk_beam_gravity", ProjectileType.GRAVITY_LANCE)
  set("atk_eye_beam", ProjectileType.EYE_BEAM)

  // ── thrown weapons ──────────────────────────────────────────────────────
  set("atk_axe_throw", ProjectileType.AXE)
  set("atk_hammer_throw", ProjectileType.HAMMER)
  set("atk_bone_throw", ProjectileType.BONE_AXE, ProjectileType.BONE_THROW,
    ProjectileType.BONE_BOOMERANG)
  set("atk_shuriken", ProjectileType.SHURIKEN)
  set("atk_knife_throw", ProjectileType.KNIFE)
  set("atk_card_throw", ProjectileType.CARD)
  set("atk_cursed_blade", ProjectileType.CURSED_BLADE)
  set("atk_holy_blade", ProjectileType.HOLY_BLADE)
  set("atk_boomerang_blade", ProjectileType.BOOMERANG_BLADE)
  set("atk_shovel_throw", ProjectileType.SHOVEL)
  set("atk_head_throw", ProjectileType.HEAD_THROW)

  // ── swung weapons, claws ────────────────────────────────────────────────
  set("atk_katana_slash", ProjectileType.KATANA)
  set("atk_sword_wave", ProjectileType.SWORD_WAVE)
  set("atk_claw_swipe", ProjectileType.CLAW_SWIPE)
  set("atk_talon_swipe", ProjectileType.TALON)
  set("atk_scythe_swing", ProjectileType.SCYTHE)
  set("atk_reap_slash", ProjectileType.REAP)

  // ── shafts ──────────────────────────────────────────────────────────────
  set("atk_spear_thrust", ProjectileType.SPEAR)
  set("atk_arrow_shot", ProjectileType.ARROW, ProjectileType.ARROW_HEAVY, ProjectileType.ARROW_LIGHT)
  set("atk_poison_arrow", ProjectileType.POISON_ARROW)
  set("atk_thorn_shot", ProjectileType.THORN, ProjectileType.THORN_LIGHT)
  set("atk_poison_dart", ProjectileType.POISON_DART)
  set("atk_stinger", ProjectileType.STINGER)

  // ── firearms and ordnance ───────────────────────────────────────────────
  set("atk_gunshot", ProjectileType.BULLET)
  set("atk_gunshot_heavy", ProjectileType.BULLET_HEAVY)
  set("atk_gunshot_light", ProjectileType.BULLET_LIGHT)
  set("atk_rocket_launch", ProjectileType.ROCKET)
  set("atk_grenade_lob", ProjectileType.GRENADE)
  set("atk_cluster_bomb", ProjectileType.CLUSTER_BOMB)
  set("atk_napalm_strike", ProjectileType.NAPALM_STRIKE)
  set("atk_mine_deploy", ProjectileType.SNARE_MINE)
  set("atk_frost_trap", ProjectileType.FROST_TRAP)
  set("atk_flask_shatter", ProjectileType.ACID_FLASK, ProjectileType.ACID_BOMB)
  set("atk_mud_bomb", ProjectileType.MUD_BOMB)
  set("atk_blight_bomb", ProjectileType.BLIGHT_BOMB)
  set("atk_ink_snare", ProjectileType.INK_SNARE)

  // ── ground slams and area effects ───────────────────────────────────────
  set("atk_quake_slam", ProjectileType.TREMOR_SLAM, ProjectileType.SEISMIC_SLAM)
  set("atk_root_burst", ProjectileType.SEISMIC_ROOT, ProjectileType.ROOT_GROWTH, ProjectileType.ENTANGLE)
  set("atk_thorn_wall", ProjectileType.THORN_WALL)
  set("atk_soul_harvest", ProjectileType.SOUL_HARVEST)
  set("atk_vortex_pull", ProjectileType.VORTEX_BOMB)
  set("atk_overclock", ProjectileType.OVERCLOCK_BEAM)
  set("atk_miasma", ProjectileType.MIASMA)
  set("atk_poison_cloud", ProjectileType.POISON_CLOUD)
  set("atk_splash", ProjectileType.SPLASH)
  set("atk_eruption", ProjectileType.ERUPTION)
  set("atk_inferno_blast", ProjectileType.INFERNO_BLAST)
  set("atk_avalanche_crush", ProjectileType.AVALANCHE_CRUSH)

  // ── waves ───────────────────────────────────────────────────────────────
  set("atk_wind_wave", ProjectileType.GUST, ProjectileType.WIND_BLADE)
  set("atk_sand_blast", ProjectileType.SAND_BLAST)
  set("atk_flame_wave", ProjectileType.FLAME_WAVE, ProjectileType.FLAME_TRAIL)
  set("atk_acid_spray", ProjectileType.ACID_SPRAY)
  set("atk_sonic_wave", ProjectileType.SONIC_WAVE)
  set("atk_sonic_boom", ProjectileType.SONIC_BOOM)
  set("atk_banshee_cry", ProjectileType.SONIC_WAVE_HEAVY)
  set("atk_harpy_screech", ProjectileType.SONIC_WAVE_MED)
  set("atk_wail_shriek", ProjectileType.WAIL)
  set("atk_momentum_strike", ProjectileType.MOMENTUM_STRIKE)

  // ── chains and ropes ────────────────────────────────────────────────────
  set("atk_chain_bolt", ProjectileType.CHAIN_BOLT, ProjectileType.LOCKDOWN_CHAIN)
  set("atk_rope_throw", ProjectileType.ROPE)

  // ── weather ─────────────────────────────────────────────────────────────
  set("atk_lightning_crack", ProjectileType.LIGHTNING)
  set("atk_chain_lightning", ProjectileType.CHAIN_LIGHTNING, ProjectileType.CHAIN_LIGHTNING_FORK,
    ProjectileType.TESLA_COIL)
  set("atk_thunder_strike", ProjectileType.THUNDER_STRIKE)
  set("atk_boulder_rumble", ProjectileType.BOULDER, ProjectileType.THROWN_BOULDER)
  set("atk_tidal_wave", ProjectileType.TIDAL_WAVE)
  set("atk_geyser_burst", ProjectileType.GEYSER)

  // ── creatures and bodies ────────────────────────────────────────────────
  set("atk_fireball", ProjectileType.FIREBALL)
  set("atk_raise_dead", ProjectileType.RAISE_DEAD)
  set("atk_tentacle_slap", ProjectileType.TENTACLE)
  set("atk_jaw_chomp", ProjectileType.JAW)
  set("atk_devour_bite", ProjectileType.DEVOUR)
  set("atk_blood_fang", ProjectileType.BLOOD_FANG)
  set("atk_bat_swarm", ProjectileType.BAT_SWARM)
  set("atk_bull_bellow", ProjectileType.HORN)
  set("atk_grab", ProjectileType.GRAB)
  set("atk_tongue_lash", ProjectileType.TONGUE)
  set("atk_web_shot", ProjectileType.WEB_SHOT, ProjectileType.WEB_TRAP)
  set("atk_punch", ProjectileType.FIST)
  set("atk_charge_fist", ProjectileType.CHARGE_FIST)

  // ── per-character overrides ─────────────────────────────────────────────
  // Same projectile, different character, different sound — because the
  // character is what the player thinks they are playing.
  only("atk_flintlock", CharacterId.Pirate, ProjectileType.BULLET)          // black powder, not a rifle
  only("atk_cannonball", CharacterId.Pirate, ProjectileType.GRENADE)
  only("atk_suppress_fire", CharacterId.MechPilot, ProjectileType.LOCKDOWN_CHAIN)
  only("atk_suppress_fire", CharacterId.Sentinel, ProjectileType.LOCKDOWN_CHAIN)
  only("atk_mech_slam", CharacterId.MechPilot, ProjectileType.SEISMIC_SLAM) // hydraulics, not earth
  only("atk_ground_pound", CharacterId.Gorilla, ProjectileType.SEISMIC_SLAM)

  only("atk_demon_fire", CharacterId.Warlock, ProjectileType.FIREBALL)      // something alive inside it
  only("atk_flambe", CharacterId.Chef, ProjectileType.FIREBALL)             // a pan going up
  only("atk_meteor", CharacterId.Astronomer, ProjectileType.FIREBALL)
  only("atk_flask_shatter", CharacterId.Alchemist, ProjectileType.FIREBALL) // a thrown potion

  only("atk_anvil_trap", CharacterId.Blacksmith, ProjectileType.SNARE_MINE)
  only("atk_rune_trap", CharacterId.Runesmith, ProjectileType.SNARE_MINE)
  only("atk_puppet_string", CharacterId.Puppeteer, ProjectileType.ROPE)
  only("atk_puppet_string", CharacterId.Puppeteer, ProjectileType.CHAIN_BOLT)
  only("atk_hypnotic_melody", CharacterId.Musician, ProjectileType.CHARM)

  only("atk_venom_spit", CharacterId.Serpent, ProjectileType.POISON_DART)
  only("atk_venom_spit", CharacterId.Scorpion, ProjectileType.POISON_DART)
  only("atk_shark_rush", CharacterId.Shark, ProjectileType.CLAW_SWIPE)      // water, then teeth

  // TREMOR_SLAM is the game's most overloaded projectile: it is the ground
  // ability for ten characters who share nothing.
  only("atk_howl", CharacterId.Wolf, ProjectileType.TREMOR_SLAM)
  only("atk_wail_shriek", CharacterId.Banshee, ProjectileType.TREMOR_SLAM)
  only("atk_harpy_screech", CharacterId.Harpy, ProjectileType.TREMOR_SLAM)
  only("atk_shield_bash", CharacterId.Crusader, ProjectileType.TREMOR_SLAM)
  only("atk_ice_quake", CharacterId.Avalanche, ProjectileType.TREMOR_SLAM)
  only("atk_shadow_burst", CharacterId.Shadowfiend, ProjectileType.TREMOR_SLAM)
  only("atk_nano_burst", CharacterId.Nanoswarm, ProjectileType.TREMOR_SLAM)

  // ── character voices on shared primaries ────────────────────────────────
  // A projectile type names the object; it does not name whoever is holding it.
  // Six characters "throw a boulder" and five "swipe a claw", and the base sound
  // can only be one of them — everyone else gets their own here, because the
  // primary attack is what a player hears for a whole match.
  only("atk_ape_throw", CharacterId.Gorilla, ProjectileType.BOULDER)
  only("atk_stone_fist", CharacterId.Golem, ProjectileType.BOULDER)
  only("atk_shell_charge", CharacterId.Beetle, ProjectileType.BOULDER)
  only("atk_ice_chunk", CharacterId.Avalanche, ProjectileType.BOULDER)
  only("atk_giant_boulder", CharacterId.Cyclops, ProjectileType.THROWN_BOULDER)
  only("atk_giant_boulder", CharacterId.Cyclops, ProjectileType.BOULDER)

  only("atk_bear_maul", CharacterId.Bear, ProjectileType.CLAW_SWIPE)
  only("atk_mantis_scythe", CharacterId.Mantis, ProjectileType.CLAW_SWIPE)
  only("atk_fenrir_rend", CharacterId.Fenrir, ProjectileType.CLAW_SWIPE)
  only("atk_ghoul_rake", CharacterId.Ghoul, ProjectileType.CLAW_SWIPE)

  only("atk_hawk_dive", CharacterId.Hawk, ProjectileType.TALON)
  only("atk_griffin_rake", CharacterId.Griffin, ProjectileType.TALON)

  only("atk_phoenix_flare", CharacterId.Phoenix, ProjectileType.FLAME_BOLT_HEAVY)
  only("atk_chimera_breath", CharacterId.Chimera, ProjectileType.FLAME_BOLT_LIGHT)
  only("atk_hellhound_spit", CharacterId.Cerberus, ProjectileType.MAGMA_BALL)

  only("atk_warlock_bolt", CharacterId.Warlock, ProjectileType.DEATH_BOLT)
  only("atk_anubis_bolt", CharacterId.Anubis, ProjectileType.DEATH_BOLT)
  only("atk_deathknight_blade", CharacterId.Deathknight, ProjectileType.CURSED_BLADE)
  only("atk_poltergeist_hurl", CharacterId.Poltergeist, ProjectileType.SOUL_BOLT_HEAVY)
  only("atk_poltergeist_hurl", CharacterId.Poltergeist, ProjectileType.CHARM)
  only("atk_djinn_bolt", CharacterId.Djinn, ProjectileType.MYSTIC_BOLT)
  only("atk_djinn_bolt", CharacterId.Djinn, ProjectileType.CHARM)

  only("atk_photon_beam", CharacterId.Photon, ProjectileType.LASER_HEAVY)
  only("atk_turret_laser", CharacterId.Sentinel, ProjectileType.LASER_LIGHT)
  only("atk_mech_gun", CharacterId.MechPilot, ProjectileType.BULLET_LIGHT)
  only("atk_tesla_arc", CharacterId.Tesla, ProjectileType.LIGHTNING)
  only("atk_tesla_arc", CharacterId.Tesla, ProjectileType.CHAIN_LIGHTNING)
  only("atk_tesla_arc", CharacterId.Tesla, ProjectileType.CHAIN_LIGHTNING_FORK)
  only("atk_time_bolt", CharacterId.Chronomancer, ProjectileType.LIGHTNING)

  only("atk_glacier_shard", CharacterId.Glacier, ProjectileType.FROST_SHARD_LIGHT)
  only("atk_medusa_spit", CharacterId.Medusa, ProjectileType.VENOM_BOLT)
  only("atk_hydra_spit", CharacterId.Hydra, ProjectileType.VENOM_BOLT_LIGHT)
  only("atk_hydra_spit", CharacterId.Hydra, ProjectileType.VENOM_BOLT)
  only("atk_treant_bark", CharacterId.Treant, ProjectileType.THORN_LIGHT)
  only("atk_inquisitor_bolt", CharacterId.Inquisitor, ProjectileType.HOLY_BOLT)

  only("atk_lute_chord", CharacterId.Bard, ProjectileType.SONIC_WAVE)
  only("atk_song_wave", CharacterId.Musician, ProjectileType.SONIC_WAVE)
  only("atk_sphinx_riddle", CharacterId.Sphinx, ProjectileType.CHARM)
  only("atk_sphinx_riddle", CharacterId.Sphinx, ProjectileType.SONIC_WAVE)
  only("atk_shift_strike", CharacterId.Shapeshifter, ProjectileType.FIST)

  /** @param characterId the shooter's character, or -1 when it isn't known. */
  def forAttack(projectileType: Byte, characterId: Byte = NO_CHAR): String = {
    if (characterId != NO_CHAR) {
      val o = overrides.get(key(characterId, projectileType))
      if (o != null) return o
    }
    val s = byType(projectileType & 0xFF)
    if (s != null) s else "atk_normal_bolt"
  }

  /** Distinct attack sound files, for preloading. */
  val allSoundNames: Seq[String] = {
    val out = scala.collection.mutable.LinkedHashSet[String]()
    byType.foreach(s => if (s != null) out += s)
    overrides.values().forEach(s => out += s)
    out.toIndexedSeq
  }
}
