load("@rules_scala//scala:scala.bzl", "scala_junit_test")

scala_junit_test(
    name = "character_selection_panel_test",
    srcs = ["CharacterSelectionPanelTest.scala"],
    env = {"GRIDGAME_AUDIO": "off"},
    suffixes = ["Test"],
    deps = [
        "//src/main/scala/com/gridgame/client:client_lib",
        "//src/main/scala/com/gridgame/common",
        "//src/test/scala/com/gridgame/client:client_test_kit",
        "@maven//:junit_junit",
        "@maven//:org_openjfx_javafx_base",
        "@maven//:org_openjfx_javafx_controls",
        "@maven//:org_openjfx_javafx_graphics",
        "@maven//:org_openjfx_javafx_base_mac_aarch64",
        "@maven//:org_openjfx_javafx_controls_mac_aarch64",
        "@maven//:org_openjfx_javafx_graphics_mac_aarch64",
    ],
)

scala_junit_test(
    name = "login_form_test",
    srcs = ["LoginFormTest.scala"],
    suffixes = ["Test"],
    deps = [
        "//src/main/scala/com/gridgame/client:client_lib",
        "@maven//:junit_junit",
    ],
)
