package com.gridgame.client.ui

import com.gridgame.common.model._
import javafx.scene.paint.Color

/** What each projectile type looks like in the character panel's ability previews
  * (AbilityPreviewRenderer): its three colours — primary, secondary, core — and the shape its
  * preview is drawn as. A type missing here is drawn in a default colour and shape. */
private[ui] object AbilityPreviewPalette {
  // (primary, secondary, core) colors per projectile type
  private val colorRegistry: Map[Byte, (Color, Color, Color)] = Map(
    ProjectileType.NORMAL       -> (Color.web("#7799cc"), Color.web("#aaccff"), Color.WHITE),
    ProjectileType.TENTACLE     -> (Color.web("#4a8060"), Color.web("#60cc80"), Color.web("#90ffb0")),
    ProjectileType.ICE_BEAM     -> (Color.web("#5090cc"), Color.web("#80ccff"), Color.web("#d0eeff")),
    ProjectileType.AXE          -> (Color.web("#aa7744"), Color.web("#cc9955"), Color.web("#eebb77")),
    ProjectileType.ROPE         -> (Color.web("#8a6633"), Color.web("#bb9955"), Color.web("#ddbb77")),
    ProjectileType.SPEAR        -> (Color.web("#8a7030"), Color.web("#ccaa44"), Color.web("#ffdd66")),
    ProjectileType.SOUL_BOLT    -> (Color.web("#6644aa"), Color.web("#9966ee"), Color.web("#cc99ff")),
    ProjectileType.HAUNT        -> (Color.web("#554488"), Color.web("#8866cc"), Color.web("#bb99ff")),
    ProjectileType.ARCANE_BOLT  -> (Color.web("#6644cc"), Color.web("#9977ff"), Color.web("#ccaaff")),
    ProjectileType.FIREBALL     -> (Color.web("#cc4400"), Color.web("#ff6600"), Color.web("#ffcc33")),
    ProjectileType.SPLASH       -> (Color.web("#2266aa"), Color.web("#4499dd"), Color.web("#77ccff")),
    ProjectileType.TIDAL_WAVE   -> (Color.web("#1155aa"), Color.web("#3388dd"), Color.web("#66bbff")),
    ProjectileType.GEYSER       -> (Color.web("#1166bb"), Color.web("#2299ee"), Color.web("#55ccff")),
    ProjectileType.BULLET       -> (Color.web("#bbaa44"), Color.web("#ddcc66"), Color.web("#ffee88")),
    ProjectileType.GRENADE      -> (Color.web("#556633"), Color.web("#778844"), Color.web("#99aa66")),
    ProjectileType.ROCKET       -> (Color.web("#884422"), Color.web("#cc6633"), Color.web("#ff9944")),
    ProjectileType.TALON        -> (Color.web("#886633"), Color.web("#bb8844"), Color.web("#ddaa66")),
    ProjectileType.GUST         -> (Color.web("#88aacc"), Color.web("#aaccee"), Color.web("#ccddff")),
    ProjectileType.SHURIKEN     -> (Color.web("#443366"), Color.web("#665588"), Color.web("#9988bb")),
    ProjectileType.POISON_DART  -> (Color.web("#447733"), Color.web("#66aa44"), Color.web("#88dd66")),
    ProjectileType.CHAIN_BOLT   -> (Color.web("#667788"), Color.web("#88aacc"), Color.web("#aaccee")),
    ProjectileType.LOCKDOWN_CHAIN -> (Color.web("#556677"), Color.web("#7799aa"), Color.web("#99bbcc")),
    ProjectileType.SNARE_MINE   -> (Color.web("#887744"), Color.web("#aaaa55"), Color.web("#cccc77")),
    ProjectileType.KATANA       -> (Color.web("#8899aa"), Color.web("#aabbcc"), Color.web("#ddeeff")),
    ProjectileType.SWORD_WAVE   -> (Color.web("#7788aa"), Color.web("#99aacc"), Color.web("#bbccee")),
    ProjectileType.PLAGUE_BOLT  -> (Color.web("#557733"), Color.web("#77aa44"), Color.web("#aadd66")),
    ProjectileType.MIASMA       -> (Color.web("#556633"), Color.web("#88aa44"), Color.web("#bbdd66")),
    ProjectileType.BLIGHT_BOMB  -> (Color.web("#668833"), Color.web("#88bb44"), Color.web("#aadd55")),
    ProjectileType.BLOOD_FANG   -> (Color.web("#881122"), Color.web("#cc2233"), Color.web("#ff4455")),
    ProjectileType.BLOOD_SIPHON -> (Color.web("#772233"), Color.web("#aa3344"), Color.web("#dd5566")),
    ProjectileType.BAT_SWARM    -> (Color.web("#662233"), Color.web("#993344"), Color.web("#cc5566")),
    // Batch 1: Elemental
    ProjectileType.FLAME_BOLT   -> (Color.web("#cc4400"), Color.web("#ff6600"), Color.web("#ffaa33")),
    ProjectileType.FROST_SHARD  -> (Color.web("#4488cc"), Color.web("#66bbff"), Color.web("#aaddff")),
    ProjectileType.LIGHTNING    -> (Color.web("#cccc22"), Color.web("#ffff44"), Color.web("#ffffaa")),
    ProjectileType.CHAIN_LIGHTNING -> (Color.web("#aaaa22"), Color.web("#dddd44"), Color.web("#ffff88")),
    ProjectileType.THUNDER_STRIKE -> (Color.web("#9999cc"), Color.web("#bbbbff"), Color.web("#ddddff")),
    ProjectileType.BOULDER      -> (Color.web("#886644"), Color.web("#aa8855"), Color.web("#ccaa77")),
    ProjectileType.SEISMIC_SLAM -> (Color.web("#776644"), Color.web("#998866"), Color.web("#bbaa88")),
    ProjectileType.WIND_BLADE   -> (Color.web("#88bbcc"), Color.web("#aaddee"), Color.web("#ccffff")),
    ProjectileType.MAGMA_BALL   -> (Color.web("#aa3300"), Color.web("#dd5500"), Color.web("#ff8833")),
    ProjectileType.ERUPTION     -> (Color.web("#992200"), Color.web("#cc4400"), Color.web("#ff7722")),
    ProjectileType.FROST_TRAP   -> (Color.web("#3377aa"), Color.web("#55aadd"), Color.web("#88ccff")),
    ProjectileType.SAND_SHOT    -> (Color.web("#aa9944"), Color.web("#ccbb66"), Color.web("#eedd88")),
    ProjectileType.SAND_BLAST   -> (Color.web("#998833"), Color.web("#bbaa55"), Color.web("#ddcc77")),
    ProjectileType.THORN        -> (Color.web("#448833"), Color.web("#66aa44"), Color.web("#88cc66")),
    ProjectileType.VINE_WHIP    -> (Color.web("#337733"), Color.web("#559955"), Color.web("#77bb77")),
    ProjectileType.THORN_WALL   -> (Color.web("#336633"), Color.web("#558855"), Color.web("#77aa77")),
    ProjectileType.INFERNO_BLAST -> (Color.web("#cc2200"), Color.web("#ff4400"), Color.web("#ffaa22")),
    ProjectileType.GLACIER_SPIKE -> (Color.web("#3366aa"), Color.web("#5599dd"), Color.web("#88ccff")),
    ProjectileType.MUD_GLOB     -> (Color.web("#665533"), Color.web("#887744"), Color.web("#aa9966")),
    ProjectileType.MUD_BOMB     -> (Color.web("#554422"), Color.web("#776633"), Color.web("#998855")),
    ProjectileType.EMBER_SHOT   -> (Color.web("#cc5500"), Color.web("#ff7700"), Color.web("#ffbb44")),
    ProjectileType.AVALANCHE_CRUSH -> (Color.web("#5577aa"), Color.web("#7799cc"), Color.web("#99bbee")),
    // Batch 2: Undead/Dark
    ProjectileType.DEATH_BOLT   -> (Color.web("#443366"), Color.web("#665588"), Color.web("#9977bb")),
    ProjectileType.RAISE_DEAD   -> (Color.web("#445533"), Color.web("#667744"), Color.web("#889966")),
    ProjectileType.BONE_AXE     -> (Color.web("#998877"), Color.web("#bbaa99"), Color.web("#ddccbb")),
    ProjectileType.BONE_THROW   -> (Color.web("#887766"), Color.web("#aa9988"), Color.web("#ccbbaa")),
    ProjectileType.WAIL         -> (Color.web("#554488"), Color.web("#7766aa"), Color.web("#aa99dd")),
    ProjectileType.SOUL_DRAIN   -> (Color.web("#553377"), Color.web("#775599"), Color.web("#9977bb")),
    ProjectileType.CLAW_SWIPE   -> (Color.web("#884433"), Color.web("#aa6644"), Color.web("#cc8866")),
    ProjectileType.DEVOUR       -> (Color.web("#772233"), Color.web("#993344"), Color.web("#bb5566")),
    ProjectileType.SCYTHE       -> (Color.web("#556677"), Color.web("#778899"), Color.web("#99aabb")),
    ProjectileType.REAP         -> (Color.web("#445566"), Color.web("#667788"), Color.web("#8899aa")),
    ProjectileType.SHADOW_BOLT  -> (Color.web("#332244"), Color.web("#554466"), Color.web("#776688")),
    ProjectileType.CURSED_BLADE -> (Color.web("#443355"), Color.web("#665577"), Color.web("#887799")),
    ProjectileType.LIFE_DRAIN   -> (Color.web("#662244"), Color.web("#884466"), Color.web("#aa6688")),
    ProjectileType.SHOVEL       -> (Color.web("#777766"), Color.web("#999988"), Color.web("#bbbbaa")),
    ProjectileType.HEAD_THROW   -> (Color.web("#556644"), Color.web("#778866"), Color.web("#99aa88")),
    ProjectileType.BANDAGE_WHIP -> (Color.web("#998866"), Color.web("#bbaa88"), Color.web("#ddccaa")),
    ProjectileType.CURSE        -> (Color.web("#553388"), Color.web("#7755aa"), Color.web("#9977cc")),
    // Batch 3: Medieval/Fantasy
    ProjectileType.HOLY_BLADE   -> (Color.web("#aa9933"), Color.web("#ccbb44"), Color.web("#eedd66")),
    ProjectileType.HOLY_BOLT    -> (Color.web("#bbaa44"), Color.web("#ddcc55"), Color.web("#ffee77")),
    ProjectileType.ARROW        -> (Color.web("#887755"), Color.web("#aa9966"), Color.web("#ccbb88")),
    ProjectileType.POISON_ARROW -> (Color.web("#558833"), Color.web("#77aa44"), Color.web("#99cc66")),
    ProjectileType.SONIC_WAVE   -> (Color.web("#7766aa"), Color.web("#9988cc"), Color.web("#bbaaee")),
    ProjectileType.SONIC_BOOM   -> (Color.web("#8877bb"), Color.web("#aa99dd"), Color.web("#ccbbff")),
    ProjectileType.FIST         -> (Color.web("#aa8866"), Color.web("#ccaa88"), Color.web("#eeccaa")),
    ProjectileType.SMITE        -> (Color.web("#ccaa33"), Color.web("#eecc44"), Color.web("#ffee66")),
    ProjectileType.CHARM        -> (Color.web("#cc44aa"), Color.web("#ee66cc"), Color.web("#ff88ee")),
    ProjectileType.CARD         -> (Color.web("#cc3333"), Color.web("#ee5555"), Color.web("#ff8888")),
    // Batch 4: Sci-Fi/Tech
    ProjectileType.DATA_BOLT    -> (Color.web("#2299aa"), Color.web("#44bbcc"), Color.web("#66ddee")),
    ProjectileType.VIRUS        -> (Color.web("#33aa44"), Color.web("#55cc66"), Color.web("#77ee88")),
    ProjectileType.LASER        -> (Color.web("#cc2222"), Color.web("#ee4444"), Color.web("#ff7777")),
    ProjectileType.GRAVITY_BALL -> (Color.web("#5533aa"), Color.web("#7755cc"), Color.web("#9977ee")),
    ProjectileType.GRAVITY_WELL -> (Color.web("#442288"), Color.web("#6644aa"), Color.web("#8866cc")),
    ProjectileType.TESLA_COIL   -> (Color.web("#aaaa22"), Color.web("#cccc44"), Color.web("#eeee66")),
    ProjectileType.NANO_BOLT    -> (Color.web("#668899"), Color.web("#88aabb"), Color.web("#aaccdd")),
    ProjectileType.VOID_BOLT    -> (Color.web("#332255"), Color.web("#554477"), Color.web("#776699")),
    ProjectileType.RAILGUN      -> (Color.web("#5588cc"), Color.web("#77aaee"), Color.web("#aaccff")),
    ProjectileType.CLUSTER_BOMB -> (Color.web("#aa4422"), Color.web("#cc6633"), Color.web("#ee8855")),
    // Batch 5: Nature/Beast
    ProjectileType.VENOM_BOLT   -> (Color.web("#447733"), Color.web("#669944"), Color.web("#88bb66")),
    ProjectileType.WEB_SHOT     -> (Color.web("#888888"), Color.web("#aaaaaa"), Color.web("#cccccc")),
    ProjectileType.STINGER      -> (Color.web("#aa8822"), Color.web("#ccaa33"), Color.web("#eecc55")),
    ProjectileType.ACID_BOMB    -> (Color.web("#559922"), Color.web("#77bb33"), Color.web("#99dd55")),
    // AoE Root
    ProjectileType.SEISMIC_ROOT -> (Color.web("#8B6914"), Color.web("#A0822B"), Color.web("#C4A04E")),
    ProjectileType.ROOT_GROWTH  -> (Color.web("#3A6B35"), Color.web("#5B8A4E"), Color.web("#7DAA6B")),
    ProjectileType.WEB_TRAP     -> (Color.web("#999999"), Color.web("#BBBBBB"), Color.web("#DDDDDD")),
    ProjectileType.TREMOR_SLAM  -> (Color.web("#7A5C3A"), Color.web("#9B7D5B"), Color.web("#BDA07E")),
    ProjectileType.ENTANGLE     -> (Color.web("#2D5A1E"), Color.web("#4A7A3A"), Color.web("#6B9B5B")),
    ProjectileType.STONE_GAZE   -> (Color.web("#666655"), Color.web("#888877"), Color.web("#AAAA99")),
    ProjectileType.INK_SNARE    -> (Color.web("#222244"), Color.web("#444466"), Color.web("#666688")),
    ProjectileType.GRAVITY_LOCK -> (Color.web("#553399"), Color.web("#7755BB"), Color.web("#9977DD")),
    // Character-specific
    ProjectileType.KNIFE       -> (Color.web("#889099"), Color.web("#aab0bb"), Color.web("#ccd0dd")),
    ProjectileType.STING       -> (Color.web("#2277cc"), Color.web("#44aaee"), Color.web("#77ccff")),
    ProjectileType.HAMMER      -> (Color.web("#665544"), Color.web("#887766"), Color.web("#aa9988")),
    ProjectileType.HORN        -> (Color.web("#aa9966"), Color.web("#ccbb88"), Color.web("#eeddaa")),
    ProjectileType.MYSTIC_BOLT -> (Color.web("#6633aa"), Color.web("#9955dd"), Color.web("#cc88ff")),
    ProjectileType.PETRIFY     -> (Color.web("#776655"), Color.web("#998877"), Color.web("#bbaa99")),
    ProjectileType.GRAB        -> (Color.web("#554422"), Color.web("#776644"), Color.web("#998866")),
    ProjectileType.JAW         -> (Color.web("#556677"), Color.web("#778899"), Color.web("#99aabb")),
    ProjectileType.TONGUE      -> (Color.web("#cc3344"), Color.web("#ee5566"), Color.web("#ff8899")),
    ProjectileType.ACID_FLASK  -> (Color.web("#228833"), Color.web("#44aa55"), Color.web("#66cc77")),
    // Plan 5a: melee and skirmisher kits
    ProjectileType.SHOCKWAVE       -> (Color.web("#aa9944"), Color.web("#ddcc66"), Color.web("#ffee99")),
    ProjectileType.ICE_QUAKE       -> (Color.web("#4477aa"), Color.web("#77aadd"), Color.web("#bbddff")),
    ProjectileType.HOWL            -> (Color.web("#667788"), Color.web("#99aabb"), Color.web("#ccddee")),
    ProjectileType.FERAL_ROAR      -> (Color.web("#aa6622"), Color.web("#dd9944"), Color.web("#ffcc77")),
    ProjectileType.EARTHSPLITTER   -> (Color.web("#776644"), Color.web("#998866"), Color.web("#bbaa88")),
    ProjectileType.GRASPING_DEAD   -> (Color.web("#888066"), Color.web("#bbb088"), Color.web("#ddd6bb")),
    ProjectileType.DEATH_GRIP      -> (Color.web("#443366"), Color.web("#665588"), Color.web("#9977bb")),
    ProjectileType.TALON_GRAB      -> (Color.web("#886633"), Color.web("#bb8844"), Color.web("#ddaa66")),
    ProjectileType.PARALYTIC_STING -> (Color.web("#447733"), Color.web("#66aa44"), Color.web("#aaee77")),
    ProjectileType.HAMMER_THROW    -> (Color.web("#666677"), Color.web("#9999aa"), Color.web("#ccccdd")),
    ProjectileType.MEAT_HOOK       -> (Color.web("#777777"), Color.web("#aaaaaa"), Color.web("#dddddd")),
    ProjectileType.FLAMBE          -> (Color.web("#cc4400"), Color.web("#ff7711"), Color.web("#ffcc44")),
    ProjectileType.HOLY_NOVA       -> (Color.web("#bbaa44"), Color.web("#ddcc55"), Color.web("#ffee77")),
    ProjectileType.AXE_SPIN        -> (Color.web("#aa7744"), Color.web("#cc9955"), Color.web("#eebb77")),
    ProjectileType.VENOM_DART      -> (Color.web("#447733"), Color.web("#66aa44"), Color.web("#88dd66")),
    ProjectileType.TOXIC_SHURIKEN  -> (Color.web("#335533"), Color.web("#558855"), Color.web("#88bb77")),
    ProjectileType.BLOOD_FRENZY    -> (Color.web("#882222"), Color.web("#aa4433"), Color.web("#dd6655")),
    ProjectileType.FLURRY          -> (Color.web("#aa8866"), Color.web("#ccaa88"), Color.web("#eeccaa")),
    ProjectileType.ROOTING_BOULDER -> (Color.web("#886644"), Color.web("#aa8855"), Color.web("#ccaa77")),
    ProjectileType.EMBER_FAN       -> (Color.web("#cc5500"), Color.web("#ff7700"), Color.web("#ffbb44")),
    ProjectileType.FENRIR_CLAW     -> (Color.web("#882233"), Color.web("#aa4444"), Color.web("#cc7766")),
    ProjectileType.GHOUL_CLAW      -> (Color.web("#556644"), Color.web("#778855"), Color.web("#99aa77")),
    ProjectileType.SHARK_CLAW      -> (Color.web("#445577"), Color.web("#667799"), Color.web("#99aabb")),
    ProjectileType.ICE_BOULDER     -> (Color.web("#5577aa"), Color.web("#7799cc"), Color.web("#99bbee")),
    ProjectileType.DRAIN_BLADE     -> (Color.web("#662244"), Color.web("#884466"), Color.web("#aa6688")),
    ProjectileType.CHILL_BLADE     -> (Color.web("#445577"), Color.web("#667799"), Color.web("#99aacc"))
  )

  def getColors(projType: Byte): (Color, Color, Color) =
    colorRegistry.getOrElse(projType, (Color.web("#7799cc"), Color.web("#aaccff"), Color.WHITE))

  // Shape categories
  sealed trait ShapeCategory
  case object Beam extends ShapeCategory
  case object Orb extends ShapeCategory
  case object Spinner extends ShapeCategory
  case object Tendril extends ShapeCategory
  case object Cloud extends ShapeCategory
  case object Dart extends ShapeCategory
  case object Chain extends ShapeCategory
  case object Mine extends ShapeCategory

  private val shapeMapping: Map[Byte, ShapeCategory] = Map(
    ProjectileType.NORMAL       -> Orb,
    ProjectileType.TENTACLE     -> Tendril,
    ProjectileType.ICE_BEAM     -> Beam,
    ProjectileType.AXE          -> Spinner,
    ProjectileType.ROPE         -> Tendril,
    ProjectileType.SPEAR        -> Dart,
    ProjectileType.SOUL_BOLT    -> Orb,
    ProjectileType.HAUNT        -> Cloud,
    ProjectileType.ARCANE_BOLT  -> Orb,
    ProjectileType.FIREBALL     -> Orb,
    ProjectileType.SPLASH       -> Orb,
    ProjectileType.TIDAL_WAVE   -> Beam,
    ProjectileType.GEYSER       -> Orb,
    ProjectileType.BULLET       -> Dart,
    ProjectileType.GRENADE      -> Mine,
    ProjectileType.ROCKET       -> Dart,
    ProjectileType.TALON        -> Dart,
    ProjectileType.GUST         -> Cloud,
    ProjectileType.SHURIKEN     -> Spinner,
    ProjectileType.POISON_DART  -> Dart,
    ProjectileType.CHAIN_BOLT   -> Chain,
    ProjectileType.LOCKDOWN_CHAIN -> Chain,
    ProjectileType.SNARE_MINE   -> Mine,
    ProjectileType.KATANA       -> Dart,
    ProjectileType.SWORD_WAVE   -> Beam,
    ProjectileType.PLAGUE_BOLT  -> Orb,
    ProjectileType.MIASMA       -> Cloud,
    ProjectileType.BLIGHT_BOMB  -> Mine,
    ProjectileType.BLOOD_FANG   -> Spinner,
    ProjectileType.BLOOD_SIPHON -> Beam,
    ProjectileType.BAT_SWARM    -> Cloud,
    // Batch 1: Elemental
    ProjectileType.FLAME_BOLT   -> Dart,
    ProjectileType.FROST_SHARD  -> Dart,
    ProjectileType.LIGHTNING    -> Beam,
    ProjectileType.CHAIN_LIGHTNING -> Chain,
    ProjectileType.THUNDER_STRIKE -> Orb,
    ProjectileType.BOULDER      -> Orb,
    ProjectileType.SEISMIC_SLAM -> Orb,
    ProjectileType.WIND_BLADE   -> Dart,
    ProjectileType.MAGMA_BALL   -> Orb,
    ProjectileType.ERUPTION     -> Orb,
    ProjectileType.FROST_TRAP   -> Mine,
    ProjectileType.SAND_SHOT    -> Dart,
    ProjectileType.SAND_BLAST   -> Cloud,
    ProjectileType.THORN        -> Dart,
    ProjectileType.VINE_WHIP    -> Tendril,
    ProjectileType.THORN_WALL   -> Dart,
    ProjectileType.INFERNO_BLAST -> Orb,
    ProjectileType.GLACIER_SPIKE -> Dart,
    ProjectileType.MUD_GLOB     -> Orb,
    ProjectileType.MUD_BOMB     -> Mine,
    ProjectileType.EMBER_SHOT   -> Dart,
    ProjectileType.AVALANCHE_CRUSH -> Orb,
    // Batch 2: Undead/Dark
    ProjectileType.DEATH_BOLT   -> Orb,
    ProjectileType.RAISE_DEAD   -> Orb,
    ProjectileType.BONE_AXE     -> Spinner,
    ProjectileType.BONE_THROW   -> Dart,
    ProjectileType.WAIL         -> Cloud,
    ProjectileType.SOUL_DRAIN   -> Beam,
    ProjectileType.CLAW_SWIPE   -> Dart,
    ProjectileType.DEVOUR       -> Spinner,
    ProjectileType.SCYTHE       -> Spinner,
    ProjectileType.REAP         -> Spinner,
    ProjectileType.SHADOW_BOLT  -> Orb,
    ProjectileType.CURSED_BLADE -> Dart,
    ProjectileType.LIFE_DRAIN   -> Beam,
    ProjectileType.SHOVEL       -> Dart,
    ProjectileType.HEAD_THROW   -> Orb,
    ProjectileType.BANDAGE_WHIP -> Tendril,
    ProjectileType.CURSE        -> Cloud,
    // Batch 3: Medieval/Fantasy
    ProjectileType.HOLY_BLADE   -> Dart,
    ProjectileType.HOLY_BOLT    -> Orb,
    ProjectileType.ARROW        -> Dart,
    ProjectileType.POISON_ARROW -> Dart,
    ProjectileType.SONIC_WAVE   -> Beam,
    ProjectileType.SONIC_BOOM   -> Cloud,
    ProjectileType.FIST         -> Spinner,
    ProjectileType.SMITE        -> Orb,
    ProjectileType.CHARM        -> Orb,
    ProjectileType.CARD         -> Spinner,
    // Batch 4: Sci-Fi/Tech
    ProjectileType.DATA_BOLT    -> Dart,
    ProjectileType.VIRUS        -> Orb,
    ProjectileType.LASER        -> Beam,
    ProjectileType.GRAVITY_BALL -> Orb,
    ProjectileType.GRAVITY_WELL -> Cloud,
    ProjectileType.TESLA_COIL   -> Chain,
    ProjectileType.NANO_BOLT    -> Dart,
    ProjectileType.VOID_BOLT    -> Orb,
    ProjectileType.RAILGUN      -> Beam,
    ProjectileType.CLUSTER_BOMB -> Mine,
    // Batch 5: Nature/Beast
    ProjectileType.VENOM_BOLT   -> Dart,
    ProjectileType.WEB_SHOT     -> Tendril,
    ProjectileType.STINGER      -> Dart,
    ProjectileType.ACID_BOMB    -> Mine,
    // AoE Root
    ProjectileType.SEISMIC_ROOT -> Cloud,
    ProjectileType.ROOT_GROWTH  -> Cloud,
    ProjectileType.WEB_TRAP     -> Tendril,
    ProjectileType.TREMOR_SLAM  -> Cloud,
    ProjectileType.ENTANGLE     -> Tendril,
    ProjectileType.STONE_GAZE   -> Cloud,
    ProjectileType.INK_SNARE    -> Cloud,
    ProjectileType.GRAVITY_LOCK -> Orb,
    // Character-specific
    ProjectileType.KNIFE       -> Dart,
    ProjectileType.STING       -> Chain,
    ProjectileType.HAMMER      -> Spinner,
    ProjectileType.HORN        -> Dart,
    ProjectileType.MYSTIC_BOLT -> Orb,
    ProjectileType.PETRIFY     -> Beam,
    ProjectileType.GRAB        -> Tendril,
    ProjectileType.JAW         -> Tendril,
    ProjectileType.TONGUE      -> Tendril,
    ProjectileType.ACID_FLASK  -> Mine,
    // Plan 5a: melee and skirmisher kits
    ProjectileType.SHOCKWAVE       -> Cloud,
    ProjectileType.ICE_QUAKE       -> Cloud,
    ProjectileType.HOWL            -> Cloud,
    ProjectileType.FERAL_ROAR      -> Cloud,
    ProjectileType.EARTHSPLITTER   -> Beam,
    ProjectileType.GRASPING_DEAD   -> Tendril,
    ProjectileType.DEATH_GRIP      -> Tendril,
    ProjectileType.TALON_GRAB      -> Tendril,
    ProjectileType.PARALYTIC_STING -> Dart,
    ProjectileType.HAMMER_THROW    -> Spinner,
    ProjectileType.MEAT_HOOK       -> Chain,
    ProjectileType.FLAMBE          -> Orb,
    ProjectileType.HOLY_NOVA       -> Orb,
    ProjectileType.AXE_SPIN        -> Spinner,
    ProjectileType.VENOM_DART      -> Dart,
    ProjectileType.TOXIC_SHURIKEN  -> Spinner,
    ProjectileType.BLOOD_FRENZY    -> Dart,
    ProjectileType.FLURRY          -> Spinner,
    ProjectileType.ROOTING_BOULDER -> Orb,
    ProjectileType.EMBER_FAN       -> Dart,
    ProjectileType.FENRIR_CLAW     -> Dart,
    ProjectileType.GHOUL_CLAW      -> Dart,
    ProjectileType.SHARK_CLAW      -> Dart,
    ProjectileType.ICE_BOULDER     -> Orb,
    ProjectileType.DRAIN_BLADE     -> Dart,
    ProjectileType.CHILL_BLADE     -> Dart
  )

  def getShape(projType: Byte): ShapeCategory =
    shapeMapping.getOrElse(projType, Orb)
}
