load("@rules_scala//scala:scala.bzl", "scala_junit_test")

scala_junit_test(
    name = "message_catalog_test",
    srcs = ["MessageCatalogTest.scala"],
    suffixes = ["Test"],
    deps = [
        "//src/main/scala/com/gridgame/client:client_lib",
        "@maven//:com_google_code_gson_gson",
        "@maven//:junit_junit",
    ],
)

scala_junit_test(
    name = "content_catalog_test",
    srcs = ["ContentCatalogTest.scala"],
    suffixes = ["Test"],
    deps = [
        "//src/main/scala/com/gridgame/client:client_lib",
        "//src/main/scala/com/gridgame/common",
        "@maven//:com_google_code_gson_gson",
        "@maven//:junit_junit",
    ],
)
